ARG BASE_TAG=24.04
ARG BASE_DEV_CONTAINER=ubuntu:${BASE_TAG}
ARG BASE_RUN_CONTAINER=ubuntu:${BASE_TAG}
ARG GO_VERSION=1.25.6
ARG ARCH
ARG OS

# Setup build container
FROM ${BASE_DEV_CONTAINER} AS build
ARG GO_VERSION
ARG ARCH
ARG OS

#RUN apt -y update \
#    && apt install -y ca-certificates build-essential libgomp1 cmake git pkg-config nasm curl \
#    && apt install -y libfreetype6-dev libmp3lame-dev libopus-dev libvorbis-dev libvpx-dev libx264-dev libx265-dev libdav1d-dev libnuma-dev \
#    && apt install -y libvulkan-dev libplacebo-dev libshaderc-dev glslang-tools glslc

RUN apt -y update \
    && apt install -y ca-certificates build-essential libgomp1 cmake git pkg-config nasm curl wget gnupg \
    && apt install -y libfreetype6-dev libmp3lame-dev libopus-dev libvorbis-dev libvpx-dev libx264-dev libx265-dev libdav1d-dev libnuma-dev \
    && wget -qO /etc/apt/trusted.gpg.d/lunarg.asc https://packages.lunarg.com/lunarg-signing-key-pub.asc \
    && echo "deb https://packages.lunarg.com/vulkan noble main" > /etc/apt/sources.list.d/lunarg-vulkan.list \
    && apt -y update \
    && apt install -y vulkan-sdk libplacebo-dev

# Install go
RUN curl -sL https://golang.org/dl/go${GO_VERSION}.${OS}-${ARCH}.tar.gz | tar -C /usr/local -xz
ENV PATH=$PATH:/usr/local/go/bin

# Copy source
WORKDIR /app
COPY . .

# Make whisper with Vulkan support
ENV GGML_VULKAN=1
RUN make clean && make -j1 

# Setup runtime container
FROM ${BASE_RUN_CONTAINER} AS runtime
RUN apt -y update \
    && apt install -y ca-certificates libgomp1 \
    && apt install -y libfreetype6 libmp3lame0 libopus0 libvorbis0a libvorbisenc2 libvpx9 libx264-164 libx265-199 libdav1d7 libnuma1 \
    && apt install -y libvulkan1 libshaderc1 libplacebo338 vulkan-tools 

# Copy built gowhisper binary
COPY --from=build --chmod=755 /app/build/gowhisper /usr/local/bin/gowhisper

# Container environment
ENV GOWHISPER_DIR="/data"
ENV GOWHISPER_ADDR="0.0.0.0:8081"
VOLUME [ "/data" ]
ENTRYPOINT [ "/usr/local/bin/gowhisper" ]
STOPSIGNAL SIGQUIT
EXPOSE 8081
